apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: gcr.io/libraryproject-447217/book-service:v1
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/book
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Password
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  type: LoadBalancer
  selector:
    app: book-service
  ports:
    - port: 8083
      targetPort: 8083
